import NavBar from '@/components/pages/Navbar/page'
import Card from '@/components/pages/Card/page'

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <Card />
        {children}</body>
    </html>
  )
}
